// Generated by scripts/import-avatar-workshop.mjs from the avatar workshop.

export default (function () {
  'use strict';
  const version = '2026-09-15-v1';
  // Display adjustments only. Approved PNGs and their anatomical anchors stay intact.
  const ranges = {
    glassesScale: [.9, 1.1], glassesDx: [-12, 12], glassesDy: [-20, 20],
    irisScale: [.6, 1.3], openness: [.3, 1.2], spacing: [-12, 12], dx: [-8, 8], dy: [-10, 10],
    browWidth: [.75, 1.25], browThickness: [.6, 1.5], browDy: [-12, 12],
    hairScale: [.95, 1.05], hairDx: [-12, 12], hairDy: [-15, 15],
    headwearScale: [.95, 1.05], headwearDx: [-12, 12], headwearDy: [-15, 15],
    mouthScale: [.75, 1.25], mouthWidth: [.75, 1.3], mouthDy: [-20, 30]
  };
  const noseRanges = { scale: [.9, 1.1], dx: [-8, 8], dy: [-8, 8] };
  const ratios = new Set(['glassesScale', 'scale', 'irisScale', 'openness', 'browWidth', 'browThickness', 'hairScale', 'headwearScale', 'mouthScale', 'mouthWidth']);
  function normalize(state, limits = ranges) {
    const result = { ...state };
    for (const [key, [min, max]] of Object.entries(limits)) {
      const value = Number.isFinite(state[key]) ? state[key] : ratios.has(key) ? 1 : 0;
      const unit = ratios.has(key) ? 100 : 1;
      result[key] = Math.max(min, Math.min(max, Math.round(value * unit) / unit));
    }
    return result;
  }
  function syncControls(scope, prefix, state, limits) {
    for (const [key, [min, max]] of Object.entries(limits)) {
      const input = scope.querySelector('#' + prefix + key); if (!input) continue;
      const unit = ratios.has(key) ? 100 : 1;
      input.min = Math.round(min * unit); input.max = Math.round(max * unit);
      input.value = Math.round(state[key] * unit); input.disabled = min === max;
      const output = scope.querySelector('#' + prefix + key + '-value');
      if (output) output.textContent = input.value + (unit === 100 ? ' %' : ' px');
    }
  }
  function create(makeCanvas) {
    const cache = new WeakMap();
    function geometry(image) {
      if (!image) return null;
      if (cache.has(image)) return cache.get(image);
      const c = makeCanvas(1024, 1024), ctx = c.getContext('2d'); ctx.drawImage(image, 0, 0);
      const pixels = ctx.getImageData(0, 0, 1024, 1024).data;
      const bounds = { left: 1024, right: 0, top: 1024, bottom: 0 }, rows = [];
      for (let y = 0; y < 1024; y++) {
        for (let x = 0; x < 1024; x++) if (pixels[(y * 1024 + x) * 4 + 3] > 8) {
          bounds.left = Math.min(bounds.left, x); bounds.right = Math.max(bounds.right, x + 1);
          bounds.top = Math.min(bounds.top, y); bounds.bottom = Math.max(bounds.bottom, y + 1);
        }
        // Central opaque run excludes ears, detached marks and transparent edge pixels.
        let left = 512, right = 512;
        while (left > 0 && pixels[(y * 1024 + left - 1) * 4 + 3] > 200) left--;
        while (right < 1024 && pixels[(y * 1024 + right) * 4 + 3] > 200) right++;
        rows.push({ left, right });
      }
      const result = { bounds, rows }; cache.set(image, result); return result;
    }
    function resolve(input, assets) {
      const state = normalize(input), limits = { ...ranges };
      const mouth = geometry(assets['mouths_' + state.mouths]);
      // Use the intersection of both heads: previews share exactly the same placement.
      const heads = ['femme', 'homme'].map(base => geometry(assets['head_' + base])).filter(Boolean);
      if (!mouth || !heads.length) return { state, limits };
      const nose = geometry(assets['nose_' + state.nose]);
      const zoneTop = nose ? 470 + (nose.bounds.bottom - 470) * (state.noseScale ?? 1) + (state.noseDy || 0) + 10 : 481;
      function fits(s) {
        const b = mouth.bounds, sx = s.mouthScale * s.mouthWidth;
        const left = 512 + (b.left - 512) * sx, right = 512 + (b.right - 512) * sx;
        const top = 535 + s.mouthDy + (b.top - 535) * s.mouthScale;
        const bottom = 535 + s.mouthDy + (b.bottom - 535) * s.mouthScale;
        if (top < zoneTop || bottom > 620) return false;
        for (const head of heads) for (let y = Math.floor(top); y < Math.ceil(bottom); y++) {
          const row = head.rows[y];
          if (!row || left < row.left + 12 || right > row.right - 12) return false;
        }
        return true;
      }
      function allowed(key, s) {
        const unit = ratios.has(key) ? 100 : 1, [min, max] = ranges[key], values = [];
        for (let n = Math.round(min * unit); n <= Math.round(max * unit); n++) if (fits({ ...s, [key]: n / unit })) values.push(n / unit);
        return values;
      }
      // An expression/model switch may invalidate the old settings. Keep scale and
      // width if a safe height exists, otherwise shrink in small uniform increments.
      if (!fits(state)) {
        const preferredHeight = state.mouthDy;
        let candidates = allowed('mouthDy', state);
        while (!candidates.length && state.mouthScale > ranges.mouthScale[0]) {
          state.mouthScale = Math.round((state.mouthScale - .01) * 100) / 100;
          candidates = allowed('mouthDy', state);
        }
        while (!candidates.length && state.mouthWidth > ranges.mouthWidth[0]) {
          state.mouthWidth = Math.round((state.mouthWidth - .01) * 100) / 100;
          candidates = allowed('mouthDy', state);
        }
        if (!candidates.length) return { state, limits, incompatible: true };
        state.mouthDy = candidates.reduce((best, y) => Math.abs(y - preferredHeight) < Math.abs(best - preferredHeight) ? y : best, candidates[0]);
      }
      // Expose only the contiguous valid interval around the current value.
      for (const key of ['mouthScale', 'mouthWidth', 'mouthDy']) {
        const values = allowed(key, state), unit = ratios.has(key) ? 100 : 1;
        let first = values.indexOf(state[key]), last = first;
        while (first > 0 && Math.round((values[first] - values[first - 1]) * unit) === 1) first--;
        while (last + 1 < values.length && Math.round((values[last + 1] - values[last]) * unit) === 1) last++;
        limits[key] = [values[first], values[last]];
      }
      return { state, limits, incompatible: false };
    }
    return { resolve, geometry };
  }
  return { version, ranges, noseRanges, normalize, syncControls, create };
})();
