// Generated by scripts/import-avatar-workshop.mjs from the avatar workshop.

export default (function(){
 'use strict';
 const defaults=()=>({schema_version:1,dx:0,dy:0,scale:1,strokes:[]});
 function validate(value){
  if(!value||value.schema_version!==1||!Array.isArray(value.strokes)||value.strokes.length>512)throw Error('Masques invalides (512 traits maximum).');
  const number=(x,min,max)=>{if(!Number.isFinite(x)||x<min||x>max)throw Error('Réglage hors limites.');return Math.round(x*100)/100;};
  let count=0;const result={schema_version:1,dx:number(value.dx,-300,300),dy:number(value.dy,-300,450),scale:number(value.scale,.5,1.75),strokes:[]};
  for(const s of value.strokes){
   if(!s||!['behind','hide'].includes(s.mask)||typeof s.erase!=='boolean'||!Array.isArray(s.points)||!s.points.length)throw Error('Trait invalide.');
   count+=s.points.length;if(count>10000)throw Error('Masque trop complexe (10 000 points maximum).');
   result.strokes.push({mask:s.mask,erase:s.erase,size:number(s.size,1,512),points:s.points.map(p=>{if(!Array.isArray(p)||p.length!==2)throw Error('Point invalide.');return [number(p[0],-2048,3072),number(p[1],-2048,3072)];})});
  }return result;
 }
 function placement(part,state,fit=part.fitting||defaults()){return {x:part.attachment.x+fit.dx+(state.headwearDx||0),y:part.attachment.y+fit.dy+(state.headwearDy||0),scale:fit.scale*Math.max(.95,Math.min(1.05,state.headwearScale??1)),anchor:part.anchor};}
 function transform(ctx,t,draw){ctx.save();ctx.translate(t.x,t.y);ctx.scale(t.scale,t.scale);ctx.translate(-t.anchor.x,-t.anchor.y);draw();ctx.restore();}
 function local(t,p){return [t.anchor.x+(p[0]-t.x)/t.scale,t.anchor.y+(p[1]-t.y)/t.scale];}
 function paint(ctx,strokes,mask){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.fillStyle=ctx.strokeStyle='#fff';for(const s of strokes){if(s.mask!==mask)continue;ctx.globalCompositeOperation=s.erase?'destination-out':'source-over';ctx.lineWidth=s.size;ctx.beginPath();ctx.arc(s.points[0][0],s.points[0][1],s.size/2,0,Math.PI*2);ctx.fill();if(s.points.length>1){ctx.beginPath();ctx.moveTo(...s.points[0]);for(const p of s.points.slice(1))ctx.lineTo(...p);ctx.stroke();}}ctx.restore();}
 function point(canvas,x,y){const r=canvas.getBoundingClientRect(),v=canvas.gobbleViewport;return [v.crop[0]+((x-r.left)*canvas.width/r.width-v.ox)/v.ratio,v.crop[1]+((y-r.top)*canvas.height/r.height-v.oy)/v.ratio];}
  function zoomCamera(camera,next,focus=[512+camera.panX,212+camera.panY]){
    const zoom=Math.max(.5,Math.min(8,Math.round(next*100)/100)),ratio=camera.zoom/zoom;
    return {zoom,panX:focus[0]+(512+camera.panX-focus[0])*ratio-512,panY:focus[1]+(212+camera.panY-focus[1])*ratio-212};
  }
  return {defaults,validate,placement,transform,local,paint,point,zoomCamera};
})();
