// Generated by scripts/import-avatar-workshop.mjs from the avatar workshop.
import dependency0 from "./lot_001_renderer.js";
import dependency1 from "./headwear-fitting.js";
export default (function(skinRenderer,F){
'use strict';
function create(makeCanvas,manifest,drafts={}){
const skin=skinRenderer.create(makeCanvas),cache=new Map();
const selected=state=>manifest.parts.find(p=>p.id===state.headwear);
const fitting=p=>drafts[p.id]||p.fitting||F.defaults();
function masks(part,state){
 const fit=fitting(part),t=F.placement(part,state,fit),key=JSON.stringify([part.id,fit,t]);if(cache.has(key))return cache.get(key);
 const behind=makeCanvas(1024,1024),hide=makeCanvas(1024,1024);
 F.paint(behind.getContext('2d'),fit.strokes,'behind');
 F.transform(hide.getContext('2d'),t,()=>F.paint(hide.getContext('2d'),fit.strokes,'hide'));
 const result={behind,hide,t};cache.set(key,result);if(cache.size>4)cache.delete(cache.keys().next().value);return result;
}
function draw(ctx,assets,state,layer=null){
 const part=selected(state);if(!part)return;const key='headwear_'+part.id,im=assets[key];if(!im)return;
 let image=skin.tinted(key,im,'hair',state.headwearColor?'custom':'native',assets[key+'_mask'],state.headwearColor);
 const m=masks(part,state);
 if(layer){const c=makeCanvas(1024,1024),lc=c.getContext('2d');lc.drawImage(image,0,0);lc.globalCompositeOperation=layer==='back'?'destination-in':'destination-out';lc.drawImage(m.behind,0,0);image=c;}
 F.transform(ctx,m.t,()=>ctx.drawImage(image,0,0));
}
function drawHair(ctx,assets,state,hair,layer){
 if(!hair)return;const part=selected(state),mode=state.headwearHair||'auto';
 if(!part||mode==='all'){hair.draw(ctx,assets,state,layer);return;}if(mode==='hide')return;
 const c=makeCanvas(1024,1024),lc=c.getContext('2d');hair.draw(lc,assets,state,layer);const m=masks(part,state);
 if(mode==='under'){
  const mask=assets['headwear_'+part.id+'_hair_keep'];if(mask){const keep=makeCanvas(1024,1024),kc=keep.getContext('2d');F.transform(kc,m.t,()=>{kc.drawImage(mask,0,0);kc.fillStyle='#fff';kc.fillRect(0,1024,1024,2048);});lc.globalCompositeOperation='destination-in';lc.drawImage(keep,0,0);}
 }
 lc.globalCompositeOperation='destination-out';lc.drawImage(m.hide,0,0);ctx.drawImage(c,0,0);
}
function overlay(ctx,assets,state){
 const part=selected(state);if(!part)return;const m=masks(part,state),c=makeCanvas(1024,1024),lc=c.getContext('2d');
 lc.drawImage(assets['headwear_'+part.id],0,0);lc.globalCompositeOperation='destination-in';lc.drawImage(m.behind,0,0);lc.globalCompositeOperation='source-in';lc.fillStyle='#00caff';lc.fillRect(0,0,1024,1024);
 ctx.save();ctx.globalAlpha=.5;F.transform(ctx,m.t,()=>ctx.drawImage(c,0,0));ctx.restore();
 lc.clearRect(0,0,1024,1024);lc.globalCompositeOperation='source-over';lc.drawImage(m.hide,0,0);lc.globalCompositeOperation='source-in';lc.fillStyle='#ff4e64';lc.fillRect(0,0,1024,1024);ctx.save();ctx.globalAlpha=.4;ctx.drawImage(c,0,0);ctx.restore();
}
function top(state){const p=selected(state);if(!p)return 0;const t=F.placement(p,state,fitting(p));return Math.min(0,t.y-t.anchor.y*t.scale-40);}
return {draw,drawHair,top,overlay};
}return {create};
})(dependency0, dependency1);
