// Generated by scripts/import-avatar-workshop.mjs from the avatar workshop.
import dependency0 from "./adjustment_limits.js";
export default (function (adjustments) {
  'use strict';
  const tones = [
    { id: 'native', label: 'Originale', color: '#f6bd91' },
    { id: 'light', label: 'Claire', color: '#ffdbc0' },
    { id: 'medium', label: 'Médium', color: '#ba8159' },
    { id: 'dark', label: 'Foncée', color: '#75482f' }
  ];
  function recolorPixels(data, mask, color, showMask = false, role = '') {
    if (!/^#[0-9a-f]{6}$/i.test(color)) throw Error('Teinte invalide');
    const mid = [1, 3, 5].map(i => parseInt(color.slice(i, i + 2), 16));
    // Lift white/pale hair without changing skin tones or the darker hair palette.
    const pale = role === 'hair' ? Math.max(0, (Math.min(...mid) / 255 - .65) / .35) : 0;
    const lift = pale * pale * (3 - 2 * pale);
    for (let i = 0; i < data.length; i += 4) {
      if (!data[i + 3]) continue;
      const weight = mask[i] / 255;
      if (!weight) continue;
      const lum = (.2126 * data[i] + .7152 * data[i + 1] + .0722 * data[i + 2]) / 255;
      const t = lum <= .70 ? lum / .70 : (lum - .70) / .30;
      for (let k = 0; k < 3; k++) {
        const original = lum <= .70 ? mid[k] * (.18 + .82 * t) : mid[k] + (255 - mid[k]) * .85 * t;
        const lightHair = lum <= .70 ? mid[k] * (.55 + .45 * Math.pow(lum / .70, .4)) : original;
        const mapped = original + (lightHair - original) * lift;
        const target = showMask ? [255, 50, 105][k] : mapped;
        const mix = showMask ? weight * .7 : weight;
        data[i + k] = Math.round(data[i + k] * (1 - mix) + target * mix);
      }
      // Coverage comes exclusively from the original PNG, never from the color mask.
    }
    return data;
  }
  function create(makeCanvas) {
    const cache = new Map();
    const pixels = new WeakMap();
    function maskPixels(mask) {
      if (!pixels.has(mask)) {
        const c = makeCanvas(1024, 1024), ctx = c.getContext('2d');
        ctx.drawImage(mask, 0, 0); pixels.set(mask, ctx.getImageData(0, 0, 1024, 1024).data);
      }
      return pixels.get(mask);
    }
    function tinted(key, img, role, toneId, mask, customColor, showMask) {
      if (toneId === 'native' && !showMask) return img;
      if (!mask) throw Error('Masque de coloration manquant : ' + key);
      const tone = tones.find(x => x.id === toneId) || { id: 'custom', color: customColor || '#ba8159' };
      const sig = key + ':' + role + ':' + tone.color + ':' + !!showMask;
      if (cache.has(sig)) return cache.get(sig);
      const c = makeCanvas(1024, 1024), ctx = c.getContext('2d');
      ctx.drawImage(img, 0, 0); const data = ctx.getImageData(0, 0, 1024, 1024), d = data.data;
      recolorPixels(d, maskPixels(mask), tone.color, showMask, role);
      if (cache.size >= 4) cache.delete(cache.keys().next().value);
      ctx.putImageData(data, 0, 0); cache.set(sig, c); return c;
    }
    function background(ctx, kind, w, h) {
      if (kind === 'transparent') return;
      ctx.fillStyle = kind === 'dark' ? '#162938' : '#f2eee5'; ctx.fillRect(0, 0, w, h);
      if (kind === 'checker') for (let y = 0; y < h; y += 20) for (let x = 0; x < w; x += 20) {
        ctx.fillStyle = (x / 20 + y / 20) % 2 ? '#b7c4ce' : '#e6ecf0'; ctx.fillRect(x, y, 20, 20);
      }
    }
    function draw(c, assets, state, options = {}) {
      state = adjustments.normalize(state, adjustments.noseRanges);
      const ctx = c.getContext('2d'), w = c.width, h = c.height;
      ctx.clearRect(0, 0, w, h); background(ctx, options.background || state.background || 'light', w, h);
      ctx.imageSmoothingEnabled = true; ctx.imageSmoothingQuality = 'high';
      const base = state.base || 'femme', nose = state.nose || 'short', tone = state.tone || 'native';
      const view = options.view || state.view || 'portrait';
      const crop = view === 'isolated' ? [402, 314, 220, 200] : view === 'face' ? [230, 100, 564, 564] : [0, 0, 1024, 1024];
      const ratio = Math.min(w / crop[2], h / crop[3]);
      ctx.save(); ctx.translate((w - crop[2] * ratio) / 2, (h - crop[3] * ratio) / 2);
      ctx.scale(ratio, ratio); ctx.translate(-crop[0], -crop[1]);
      if (view !== 'isolated') for (const role of ['bust', 'head']) {
        const key = role + '_' + base; ctx.drawImage(tinted(key, assets[key], role, tone, assets[key + '_mask'], state.customColor, state.showMask), 0, 0);
      }
      if (state.visible !== false) {
        const key = 'nose_' + nose;
        const img = tinted(key, assets[key], 'nose', tone, assets[key + '_mask'], state.customColor, state.showMask);
        ctx.save(); ctx.translate(512 + (state.dx || 0), 470 + (state.dy || 0));
        const scale = state.scale === undefined ? 1 : state.scale;
        ctx.scale(scale, scale); ctx.drawImage(img, -512, -470); ctx.restore();
      }
      ctx.restore();
    }
    return { draw, tinted, background };
  }
  return { create, tones, recolorPixels };
})(dependency0);
