// Generated by scripts/import-avatar-workshop.mjs from the avatar workshop.
import dependency0 from "./lot_001_renderer.js";
import dependency1 from "./adjustment_limits.js";
import dependency2 from "./background-renderer.js";
import dependency3 from "./aura-renderer.js";
export default (function (skinRenderer, adjustments, backgrounds, auras) {
  'use strict';
  function irisRect(center, spriteDiameter, scale, spacing = 0, dx = 0, dy = 0) {
    const size = center.iris_diameter * scale * 256 / spriteDiameter;
    return { x: center.x + (center.side === 'left' ? -spacing : spacing) + dx - size / 2, y: center.y + dy - size / 2, size };
  }
  function create(makeCanvas, manifest) {
    let facialhair = null, clothes = null, glasses = null, decorations = null, hair = null, mouths = null, headwear = null;
    const constraints = adjustments.create(makeCanvas);
    const skin = skinRenderer.create(makeCanvas), irisCache = new Map(), pairCache = new Map();
    function tintedIris(part, assets, color) {
      const key = part.id + ':' + color;
      if (irisCache.has(key)) return irisCache.get(key);
      const c = makeCanvas(256, 256), ctx = c.getContext('2d'), mask = makeCanvas(256, 256);
      ctx.drawImage(assets['eye_' + part.id + '_iris'], 0, 0);
      const d = ctx.getImageData(0, 0, 256, 256);
      mask.getContext('2d').drawImage(assets['eye_' + part.id + '_iris_color'], 0, 0);
      skinRenderer.recolorPixels(d.data, mask.getContext('2d').getImageData(0, 0, 256, 256).data, color || '#a6692c');
      ctx.putImageData(d, 0, 0);
      if (irisCache.size > 4) irisCache.delete(irisCache.keys().next().value);
      irisCache.set(key, c); return c;
    }
    function placeLids(ctx, image, state) {
      const gap = state.spacing || 0;
      ctx.save(); ctx.translate(state.dx || 0, 390 + (state.dy || 0)); ctx.scale(1, state.openness ?? 1);
      ctx.drawImage(image, 0, 0, 512, 1024, -gap, -390, 512, 1024);
      ctx.drawImage(image, 512, 0, 512, 1024, 512 + gap, -390, 512, 1024); ctx.restore();
    }
    function pair(part, assets, state, openingOnly = false) {
      const key = JSON.stringify([part.id, state.tone, state.customColor, state.irisColor, state.irisScale, state.openness, state.spacing, state.dx, state.dy, state.irisVisible, state.showMask, openingOnly]);
      if (pairCache.has(key)) return pairCache.get(key);
      const c = makeCanvas(1024, 1024), ctx = c.getContext('2d'), id = 'eye_' + part.id;
      if (part.minimalStyle) {
        for (const center of part.eye_centers) {
          const x = center.x + (center.side === 'left' ? -1 : 1) * (state.spacing || 0) + (state.dx || 0), y = center.y + (state.dy || 0);
          if (part.minimalStyle === 'dots' || openingOnly) {
            ctx.fillStyle = openingOnly ? '#fff' : '#252124';
            ctx.beginPath(); ctx.arc(x, y, center.iris_diameter * (state.irisScale ?? 1) / 2, 0, Math.PI * 2); ctx.fill();
          } else {
            const r = irisRect(center, part.iris.sprite_diameter, state.irisScale ?? 1, state.spacing, state.dx, state.dy);
            ctx.drawImage(tintedIris(part, assets, state.irisColor), r.x, r.y, r.size, r.size);
          }
        }
      }
      else if (openingOnly) placeLids(ctx, assets[id + '_opening'], state);
      else {
        const art = skin.tinted(id, assets[id], 'eyes', state.tone || 'native', assets[id + '_skin'], state.customColor, state.showMask);
        placeLids(ctx, art, state);
        if (state.irisVisible !== false) {
          const layer = makeCanvas(1024, 1024), lc = layer.getContext('2d'), iris = tintedIris(part, assets, state.irisColor);
          for (const center of part.eye_centers) {
            const r = irisRect(center, part.iris.sprite_diameter, state.irisScale ?? 1, state.spacing, state.dx, state.dy);
            lc.drawImage(iris, r.x, r.y, r.size, r.size);
          }
          const opening = makeCanvas(1024, 1024); placeLids(opening.getContext('2d'), assets[id + '_opening'], state);
          lc.globalCompositeOperation = 'destination-in'; lc.drawImage(opening, 0, 0);
          lc.globalCompositeOperation = 'source-over'; ctx.drawImage(layer, 0, 0);
        }
      }
      if (pairCache.size > 4) pairCache.delete(pairCache.keys().next().value);
      pairCache.set(key, c); return c;
    }
    function draw(canvas, assets, state, options = {}) {
      const resolved = constraints.resolve(state, assets);
      state = resolved.incompatible ? { ...resolved.state, mouths: '' } : resolved.state;
      const ctx = canvas.getContext('2d'), w = canvas.width, h = canvas.height;
      ctx.clearRect(0, 0, w, h); skin.background(ctx, options.background || state.background || 'light', w, h);
      ctx.imageSmoothingEnabled = true; ctx.imageSmoothingQuality = 'high';
      const part = manifest.parts.find(p => p.id === state.eyes) || manifest.parts[0], view = options.authoring ? 'portrait' : options.view || state.view || 'portrait';
      if (view === 'nose') { skin.draw(canvas, assets, { ...state, visible: true, scale: 1, dx: 0, dy: 0 }, { view: 'isolated', background: options.background || state.background }); return; }
      if (['portrait', 'face', 'backdrops'].includes(view) && !options.authoring) backgrounds.draw(ctx, assets, state, w, h);
      if (view === 'backdrops') return;
      if (view === 'auras') {
        const ratio = Math.min(w, h) / 1024;
        ctx.save(); ctx.translate((w - 1024 * ratio) / 2, (h - 1024 * ratio) / 2); ctx.scale(ratio, ratio);
        auras.draw(ctx, assets, state); ctx.restore(); return;
      }
      if (state.eyes && !assets['eye_' + part.id]) return;
      if (view === 'hair' || view === 'hairFront' || view === 'hairBack' || view === 'hairOcclusion') {
        ctx.save(); const ratio = Math.min(w, h) / 1024; ctx.translate((w - 1024 * ratio) / 2, (h - 1024 * ratio) / 2); ctx.scale(ratio, ratio);
        if (hair) hair.draw(ctx, assets, state, view === 'hairFront' ? 'front' : view === 'hairBack' ? 'back' : view === 'hairOcclusion' ? 'occlusion' : null); ctx.restore(); return;
      }
      if (view === 'headwear') {
        const top=headwear?.top(state)||0, ratio = Math.min(w / 760, h / (470-top)); ctx.save(); ctx.translate(w / 2, h / 2); ctx.scale(ratio, ratio); ctx.translate(-512, -(470+top)/2);
        if (headwear) headwear.draw(ctx, assets, state); ctx.restore(); return;
      }
      if(view==='facialhair'){
        const ratio=Math.min(w/480,h/580);ctx.save();ctx.translate(w/2,h/2);ctx.scale(ratio,ratio);ctx.translate(-512,-630);
        if(facialhair)facialhair.draw(ctx,assets,state);ctx.restore();return;
      }
      if(view==='clothes'){
        const ratio=Math.min(w/940,h/560);ctx.save();ctx.translate(w/2,h/2);ctx.scale(ratio,ratio);ctx.translate(-512,-740);
        if(!clothes||!clothes.draw(ctx,assets,state)){const id='bust_'+(state.base||'femme');ctx.drawImage(skin.tinted(id,assets[id],'bust',state.tone||'native',assets[id+'_mask'],state.customColor,state.showMask),0,0);}ctx.restore();return;
      }
      if (view === 'glasses') {
        const ratio=Math.min(w/480,h/280);ctx.save();ctx.translate(w/2,h/2);ctx.scale(ratio,ratio);ctx.translate(-512,-390);
        if(glasses)glasses.draw(ctx,assets,state);ctx.restore();return;
      }
      if (view === 'mouths') {
        const ratio = Math.min(w / 420, h / 300);
        ctx.save(); ctx.translate(w / 2, h / 2); ctx.scale(ratio, ratio); ctx.translate(-512, -535);
        if (mouths) mouths.draw(ctx, assets, state); ctx.restore(); return;
      }
      if (view === 'iris') {
        if (!state.eyes) return;
        const side = Math.min(w, h) * .8, iris = tintedIris(part, assets, state.irisColor);
        ctx.drawImage(iris, (w - side) / 2, (h - side) / 2, side, side); return;
      }
      const decorOnly = view === 'lashes' || view === 'brows';
      const isolated = decorOnly || view === 'isolated' || view === 'opening';
      const top=headwear?.top(state)||0;
      let crop = decorOnly ? [290, 185, 444, 360] : isolated ? [316, 242, 392, 288] : view === 'face' ? (state.hair || state.headwear ? [130, top, 764, 764-top] : [230, 100, 564, 564]) : [0, top, 1024, 1024-top];
      if(options.authoring){const size=1024/(options.zoom||1);crop=[512+(options.panX||0)-size/2,212+(options.panY||0)-size/2,size,size];}
      const ratio = Math.min(w / crop[2], h / crop[3]);
      // Frame the whole assembled bust lower; every part and its masks share this translation.
      // Authoring and isolated views retain their original coordinate system.
      const avatarDy = view === 'portrait' && !options.authoring ? 128 : 0;
      canvas.gobbleViewport={crop,ratio,ox:(w-crop[2]*ratio)/2,oy:(h-crop[3]*ratio)/2+avatarDy*ratio};
      ctx.save(); ctx.translate((w - crop[2] * ratio) / 2, (h - crop[3] * ratio) / 2); ctx.scale(ratio, ratio); ctx.translate(-crop[0], -crop[1]);
      ctx.translate(0, avatarDy);
      if (!isolated) {
        if (!options.authoring) auras.draw(ctx, assets, state);
        if (headwear) headwear.draw(ctx, assets, state, 'back');
        if (headwear) headwear.drawHair(ctx, assets, state, hair, 'back'); else if (hair) hair.draw(ctx, assets, state, 'back');
        for (const role of ['bust', 'head']) {
          if (role === 'head') options.drawAccessories?.(ctx, 'neck');
          if(role==='bust'&&clothes&&clothes.draw(ctx,assets,state))continue;
          const id = role + '_' + (state.base || 'femme');
          ctx.drawImage(skin.tinted(id, assets[id], role, state.tone || 'native', assets[id + '_mask'], state.customColor, state.showMask), 0, 0);
        }
      }
      if (state.eyes && !decorOnly && state.visible !== false) ctx.drawImage(pair(part, assets, state, view === 'opening'), 0, 0);
      if (decorations && view !== 'opening') decorations.draw(ctx, assets, state, view);
      if (!isolated && state.nose && assets['nose_' + state.nose]) {
        const id = 'nose_' + state.nose;
        ctx.save(); ctx.translate(512 + (state.noseDx || 0), 470 + (state.noseDy || 0)); ctx.scale(state.noseScale ?? 1, state.noseScale ?? 1); ctx.drawImage(skin.tinted(id, assets[id], 'nose', state.tone || 'native', assets[id + '_mask'], state.customColor, state.showMask), -512, -470); ctx.restore();
      }
      if (!isolated && mouths) mouths.draw(ctx, assets, state);
      if (!isolated && facialhair) facialhair.draw(ctx, assets, state);
      if (!isolated) options.drawAccessories?.(ctx, 'face');
      if (!isolated) {
        if (headwear) headwear.drawHair(ctx, assets, state, hair, 'front');
        else if (hair) hair.draw(ctx, assets, state, 'front');
        if (glasses) glasses.draw(ctx, assets, state);
        if (headwear) headwear.draw(ctx, assets, state, 'front');
      }
      if(options.authoring && options.overlay && headwear) headwear.overlay(ctx,assets,state);
      ctx.restore();
    }
    return { draw, resolve: (state, assets) => constraints.resolve(state, assets), setDecorations(value) { decorations = value; }, setHair(value) { hair = value; }, setMouths(value) { mouths = value; }, setFacialHair(value) { facialhair = value; }, setClothes(value) { clothes = value; }, setGlasses(value) { glasses = value; }, setHeadwear(value) { headwear = value; } };
  }
  return { create, irisRect, tones: skinRenderer.tones };
})(dependency0, dependency1, dependency2, dependency3);
