// Generated by scripts/import-avatar-workshop.mjs from the avatar workshop.
import dependency0 from "./lot_001_renderer.js";
export default (function(skinRenderer){
 'use strict';
 function selected(manifest,state){return state.base==='homme'?manifest.parts.find(p=>p.id===state.facialhair)||null:null;}
 function create(makeCanvas,manifest){
  const color=skinRenderer.create(makeCanvas);
  function draw(ctx,assets,state){
   const part=selected(manifest,state);if(!part)return false;
   const key='facialhair_'+part.id,source=assets[key];if(!source)return false;
   const art=color.tinted(key,source,'hair',state.facialhairColor?'custom':'native',assets[key+'_mask'],state.facialhairColor);
   ctx.drawImage(art,0,0);return true;
  }
  return {draw};
 }
 return {create,selected};
})(dependency0);
