// Generated by scripts/import-avatar-workshop.mjs from the avatar workshop.
import dependency0 from "./lot_001_renderer.js";
export default (function (skinRenderer) {
  'use strict';
  function browRect(center, state, top) {
    return { x: center.x + (center.side === 'left' ? -1 : 1) * (state.spacing || 0) + (state.dx || 0),
      y: top - 45 + (state.dy || 0) + (state.browDy || 0), width: state.browWidth ?? 1, thickness: state.browThickness ?? 1 };
  }
  function create(makeCanvas, lots) {
    const curves = new Map(), cache = new Map(), colors = new Map();
    function boundaries(assets, eyes) {
      if (!eyes || !assets['eye_' + eyes + '_opening']) return [[], []];
      if (curves.has(eyes)) return curves.get(eyes);
      const c = makeCanvas(1024, 1024), ctx = c.getContext('2d'); ctx.drawImage(assets['eye_' + eyes + '_opening'], 0, 0);
      const data = ctx.getImageData(0, 0, 1024, 1024).data;
      const result = [0, 512].map(start => {
        const cols = [];
        for (let x = start; x < start + 512; x++) for (let y = 0; y < 1024; y++) if (data[(y * 1024 + x) * 4 + 3] > 32) { cols.push({ x, y }); break; }
        return cols;
      });
      curves.set(eyes, result); return result;
    }
    function art(assets, key, state) {
      if (!state.hairColor) return assets[key];
      const id = key + ':' + state.hairColor; if (colors.has(id)) return colors.get(id);
      const c = makeCanvas(1024, 1024), ctx = c.getContext('2d'), m = makeCanvas(1024, 1024);
      ctx.drawImage(assets[key], 0, 0); m.getContext('2d').drawImage(assets[key + '_mask'], 0, 0);
      const pixels = ctx.getImageData(0, 0, 1024, 1024); skinRenderer.recolorPixels(pixels.data, m.getContext('2d').getImageData(0, 0, 1024, 1024).data, state.hairColor); ctx.putImageData(pixels, 0, 0);
      if (colors.size > 4) colors.delete(colors.keys().next().value); colors.set(id, c); return c;
    }
    function layer(assets, state, kind) {
      const part = lots[kind].parts.find(p => p.id === state[kind]); if (!part) return null;
      const key = JSON.stringify([kind, part.id, state.eyes, state.openness, state.spacing, state.dx, state.dy, state.browWidth, state.browThickness, state.browDy, state.hairColor]);
      if (cache.has(key)) return cache.get(key);
      const c = makeCanvas(1024, 1024), ctx = c.getContext('2d'), image = art(assets, kind + '_' + part.id, state), paths = boundaries(assets, state.eyes);
      if (kind === 'brows') {
        for (const [i, center] of part.brow_centers.entries()) {
          const top = paths[i].length ? Math.min(...paths[i].map(p => p.y)) : 345;
          const r = browRect(center, state, top);
          ctx.save(); ctx.translate(r.x, r.y); ctx.scale(r.width, r.thickness);
          ctx.drawImage(image, i * 512, 0, 512, 1024, i * 512 - center.x, -center.y, 512, 1024); ctx.restore();
        }
      } else {
        for (const [i, strip] of part.lash_strips.entries()) {
          const cols = paths[i]; if (!cols.length) continue;
          const box = strip.box, gap = (i ? 1 : -1) * (state.spacing || 0);
          const sourceHeight = Math.max(1, Math.max(...strip.roots) - box.top), sy = part.lash_height / sourceHeight;
          for (let n = 0; n < cols.length; n++) {
            const u = n / Math.max(1, cols.length - 1), sourceX = Math.min(box.width - 1, Math.round(u * (box.width - 1)));
            const root = strip.roots[sourceX], base = 390 + (cols[n].y - 390) * (state.openness ?? 1) + (state.dy || 0) - 1;
            ctx.drawImage(image, box.left + sourceX, box.top, 1, box.height, cols[n].x + gap + (state.dx || 0), base + (box.top - root) * sy, 1.15, box.height * sy);
          }
        }
      }
      if (cache.size > 4) cache.delete(cache.keys().next().value); cache.set(key, c); return c;
    }
    function draw(ctx, assets, state, view) {
      for (const kind of ['lashes', 'brows']) {
        if ((view === 'lashes' || view === 'brows') && view !== kind) continue;
        if (kind === 'lashes' && state.visible === false && view !== 'lashes') continue;
        const image = layer(assets, state, kind); if (image) ctx.drawImage(image, 0, 0);
      }
    }
    return { draw, boundaries };
  }
  return { create, browRect };
})(dependency0);
