// Generated by scripts/import-avatar-workshop.mjs from the avatar workshop.
import dependency0 from "./lot_001_renderer.js";
export default (function(skinRenderer){
 'use strict';
 function selected(manifest,state){
  const part=manifest.parts.find(p=>p.id===state.clothes);if(!part)return null;
  if(part.base===(state.base||'femme'))return part;
  return part.counterpart ? manifest.parts.find(p=>p.id===part.counterpart&&p.base===(state.base||'femme'))||null : null;
 }
 function create(makeCanvas,manifest){
  const color=skinRenderer.create(makeCanvas),skin=skinRenderer.create(makeCanvas);
  function draw(ctx,assets,state){
   const part=selected(manifest,state);if(!part)return false;
   const key='clothes_'+part.id,source=assets[key];if(!source)return false;
   const fabric=color.tinted(key,source,'hair',state.clothesColor?'custom':'native',assets[key+'_mask'],state.clothesColor);
   const image=skin.tinted(key+':'+(state.clothesColor||'native'),fabric,'bust',state.tone||'native',assets[key+'_skin'],state.customColor,state.showMask);
   ctx.drawImage(image,0,0);return true;
  }
  return {draw,selected:state=>selected(manifest,state)};
 }
 return {create,selected};
})(dependency0);
