// Generated by scripts/import-avatar-workshop.mjs from the avatar workshop.
import dependency0 from "./lot_001_renderer.js";
export default (function (skinRenderer) {
  'use strict';
  function transform(state, anchor = { x: 512, y: 535 }) {
    const scale = state.mouthScale ?? 1;
    return { x: anchor.x, y: anchor.y + (state.mouthDy || 0), scaleX: scale * (state.mouthWidth ?? 1), scaleY: scale };
  }
  function create(makeCanvas, manifest) {
    const skin = skinRenderer.create(makeCanvas);
    function draw(ctx, assets, state) {
      const part = manifest.parts.find(p => p.id === state.mouths); if (!part) return;
      const key = 'mouths_' + part.id, im = assets[key]; if (!im) return;
      const image = skin.tinted(key, im, 'mouths', state.mouthColor ? 'custom' : 'native', assets[key + '_mask'], state.mouthColor);
      const anchor = part.anchor || { x: 512, y: 535 }, t = transform(state, anchor);
      ctx.save(); ctx.translate(t.x, t.y); ctx.scale(t.scaleX, t.scaleY); ctx.drawImage(image, -anchor.x, -anchor.y); ctx.restore();
    }
    return { draw };
  }
  return { create, transform };
})(dependency0);
