// Generated by scripts/import-avatar-workshop.mjs from the avatar workshop.
import dependency0 from "./lot_001_renderer.js";
import dependency1 from "./hair-fitting.js";
export default (function (skinRenderer,F) {
  'use strict';
  function create(makeCanvas, manifest, drafts = {}) {
    const skin = skinRenderer.create(makeCanvas), cache = new Map();
    const fitting=F.create(makeCanvas),multiplyCache=new Map();
    function tint(key,image,mask,color,part) {
      if(!color||part.coloration?.method!=='multiply')return skin.tinted(key,image,'hair',color?'custom':'native',mask,color);
      const signature=key+'|'+color;if(multiplyCache.has(signature))return multiplyCache.get(signature);
      const c=makeCanvas(1024,1024),ctx=c.getContext('2d');ctx.drawImage(image,0,0);
      const pixels=ctx.getImageData(0,0,1024,1024),rgb=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16)/255);
      for(let i=0;i<pixels.data.length;i+=4)for(let j=0;j<3;j++)pixels.data[i+j]=Math.round(pixels.data[i+j]*rgb[j]);
      ctx.putImageData(pixels,0,0);multiplyCache.set(signature,c);if(multiplyCache.size>4)multiplyCache.delete(multiplyCache.keys().next().value);return c;
    }
    function draw(ctx, assets, state, layer) {
      const part = manifest.parts.find(p => p.id === state.hair); if (!part) return;
      const fit=drafts[part.id]||part.fitting;
      if(fit&&!state.hairPrevious&&(fit.dx||fit.dy||fit.scale!==1||fit.strokes.length)) {
        const result=fitting.prepare(assets,state,part,fit,tint);
        const image=result?.[layer==='occlusion'?'behind':layer||'full'];if(image)ctx.drawImage(image,0,0);return;
      }
      const previous = state.hairPrevious && part.previous_version;
      const key = 'hair_' + part.id + (previous ? '_previous' : '');
      const version = previous || part;
      if (version.layer_partition?.method === 'lower_head_occlusion') {
        const mask = assets[key + '_lower_head_' + (state.base || 'femme')];
        if (layer === 'occlusion') { if (mask) ctx.drawImage(mask, 0, 0); return; }
        const im = assets[key]; if (!im || !mask) return;
        const cacheKey = JSON.stringify([key, state.base, state.hairColor, state.hairDx, state.hairDy, state.hairScale, layer]);
        if (!cache.has(cacheKey)) {
          const c = makeCanvas(1024, 1024), cc = c.getContext('2d');
          const image = skin.tinted(key, im, 'hair', state.hairColor ? 'custom' : 'native', assets[key + '_mask'], state.hairColor);
          cc.save(); cc.translate(512 + (state.hairDx || 0), 120 + (state.hairDy || 0)); cc.scale(state.hairScale ?? 1, state.hairScale ?? 1); cc.drawImage(image, -512, -120); cc.restore();
          // The anatomical mask stays fixed while the hair moves.
          if (layer === 'front' || layer === 'back') {
            cc.globalCompositeOperation = layer === 'front' ? 'destination-out' : 'destination-in';
            cc.drawImage(mask, 0, 0); cc.globalCompositeOperation = 'source-over';
          }
          if (cache.size > 4) cache.clear(); cache.set(cacheKey, c);
        }
        ctx.drawImage(cache.get(cacheKey), 0, 0); return;
      }
      if (layer === 'occlusion') return;
      const id = key + (layer ? '_' + layer : ''), im = assets[id]; if (!im) return;
      const image = tint(id, im, assets[key + '_mask'], state.hairColor, version);
      ctx.save(); ctx.translate(512 + (state.hairDx || 0), 120 + (state.hairDy || 0)); ctx.scale(state.hairScale ?? 1, state.hairScale ?? 1); ctx.drawImage(image, -512, -120); ctx.restore();
    }
    return { draw, overlay(ctx,assets,state) {
      const part=manifest.parts.find(p=>p.id===state.hair);if(!part||state.hairPrevious)return;
      fitting.overlay(ctx,fitting.prepare(assets,state,part,drafts[part.id]||part.fitting||F.defaults(),tint));
    } };
  }
  return { create };
})(dependency0, dependency1);
