// Generated by scripts/import-avatar-workshop.mjs from the avatar workshop.
import dependency0 from "./lot_001_renderer.js";
export default (function (skinRenderer) {
  'use strict';
  function transform(state, anchor = { x: 512, y: 390 }) {
    const scale = state.glassesScale ?? 1;
    return { x: anchor.x + (state.glassesDx || 0), y: anchor.y + (state.glassesDy || 0), scaleX: scale, scaleY: scale };
  }
  function create(makeCanvas, manifest) {
    const skin = skinRenderer.create(makeCanvas);
    function draw(ctx, assets, state) {
      const part = manifest.parts.find(p => p.id === state.glasses); if (!part) return;
      const key = 'glasses_' + part.id, im = assets[key]; if (!im) return;
      const image = skin.tinted(key, im, 'hair', state.glassesColor ? 'custom' : 'native', assets[key + '_mask'], state.glassesColor);
      const anchor = part.anchor || { x: 512, y: 390 }, t = transform(state, anchor);
      ctx.save(); ctx.translate(t.x, t.y); ctx.scale(t.scaleX, t.scaleY); ctx.drawImage(image, -anchor.x, -anchor.y); ctx.restore();
    }
    return { draw };
  }
  return { create, transform };
})(dependency0);
