import { createStateFeature } from "../../app/core/createStateFeature.js";
import { createEmptyAuthForm } from "../../components/auth/authFormModel.js";

export function createInitialOverlaysState() {
  return {
    aboutOpen: false,
    accountMenuOpen: false,
    accountNotice: "",
    authError: "",
    authForm: createEmptyAuthForm(),
    authInfo: "",
    authModalMode: null,
    authSubmitting: false,
    broadcastNotice: {
      error: "",
      loading: false,
      message: null,
    },
    definitionModal: {
      definitions: [],
      definition: "",
      etymology: "",
      fromVault: false,
      fromWordInfo: false,
      inflectionBase: "",
      inflectionGuess: false,
      inflectionLabel: "",
      lemma: "",
      lemmaGuess: false,
      lemmaLabel: "",
      loading: false,
      matchedTitle: "",
      ok: false,
      open: false,
      participleBase: "",
      participleGuess: false,
      participleLabel: "",
      phraseGuess: false,
      preferLongDefinition: false,
      source: "",
      title: "",
      url: "",
      word: "",
    },
    facebookInviteOpen: false,
    helpOpen: false,
    keyboardMenuOpen: false,
    mobileExitConfirmOpen: false,
    patchNotesOpen: false,
    playerProfileModal: {
      error: "",
      loading: false,
      open: false,
      profile: null,
      userId: null,
      nick: "",
    },
    playersOverlayMode: "snapshot",
    playersOverlayOpen: false,
    playersOverlaySnapshot: [],
    popupDistinctVisitDays: 0,
    recordModal: {
      categoryKey: "",
      categoryLabel: "",
      nick: "",
      open: false,
      pts: null,
      rank: null,
      rankTotal: null,
      records: [],
      timeMs: null,
      word: "",
      wordsCount: null,
    },
    roundPlayerModal: {
      allWords: [],
      anchorRect: null,
      nick: "",
      open: false,
      records: [],
      targetBoardEntries: [],
      targetBoardKey: "",
      targetBoardLabel: "",
      words: [],
    },
    settingsOpen: false,
    soundMenuOpen: false,
    supportModalSection: "support",
    supportOpen: false,
    trainingConfirm: null,
    trainingBusy: false,
    visualMenuOpen: false,
    vaultWordOfDayPopup: {
      dateId: "",
      definition: "",
      displayWord: "",
      open: false,
      source: "",
      url: "",
      word: "",
    },
    wordInfoModal: {
      foundBy: [],
      open: false,
      word: "",
    },
  };
}

export function createOverlaysFeature(context) {
  return createStateFeature(context, createInitialOverlaysState);
}
