// Generated by scripts/prepare-avatar-additions.py; original imagegen PNGs remain intact.
export const AVATAR_ADDITION_IMAGES = Object.freeze({
  "witch_nose": {
    "file": "additions/2026-09-22/witch_nose.png",
    "sourceBounds": [
      299,
      92,
      656,
      1038
    ],
    "preview": {
      "width": 1254,
      "height": 1254,
      "viewBox": [
        -70.54,
        29.72,
        1395.07,
        1162.56
      ]
    }
  },
  "button_nose": {
    "file": "additions/2026-09-22/button_nose.png",
    "sourceBounds": [
      239,
      256,
      776,
      733
    ],
    "preview": {
      "width": 1254,
      "height": 1254,
      "viewBox": [
        134.42,
        212.02,
        985.15,
        820.96
      ]
    }
  },
  "crooked_nose": {
    "file": "additions/2026-09-22/crooked_nose.png",
    "sourceBounds": [
      235,
      115,
      790,
      975
    ],
    "preview": {
      "width": 1254,
      "height": 1254,
      "viewBox": [
        -25.2,
        56.5,
        1310.4,
        1092.0
      ]
    }
  },
  "earrings_hoops": {
    "file": "additions/2026-09-22/earrings_hoops.png",
    "sourceBounds": [
      95,
      84,
      1064,
      1079
    ],
    "preview": {
      "width": 1254,
      "height": 1254,
      "viewBox": [
        -98.09,
        19.26,
        1450.18,
        1208.48
      ]
    }
  },
  "earrings_pearls": {
    "file": "additions/2026-09-22/earrings_pearls.png",
    "sourceBounds": [
      394,
      82,
      457,
      1093
    ],
    "preview": {
      "width": 1254,
      "height": 1254,
      "viewBox": [
        -112.0,
        16.42,
        1468.99,
        1224.16
      ]
    }
  },
  "earrings_stars": {
    "file": "additions/2026-09-22/earrings_stars.png",
    "sourceBounds": [
      333,
      64,
      588,
      1089
    ],
    "preview": {
      "width": 1254,
      "height": 1254,
      "viewBox": [
        -104.81,
        -1.34,
        1463.62,
        1219.68
      ]
    }
  },
  "earrings_gems": {
    "file": "additions/2026-09-22/earrings_gems.png",
    "sourceBounds": [
      373,
      34,
      498,
      1180
    ],
    "preview": {
      "width": 1254,
      "height": 1254,
      "viewBox": [
        -170.96,
        -36.8,
        1585.92,
        1321.6
      ]
    }
  }
});
