// Generated by scripts/prepare-avatar-cosmetics.py; pixels remain unchanged.
export const AVATAR_COSMETIC_IMAGES = {
  "pirate_eyepatch": {
    "file": "candidates/accessories/lot_013/2026-09-20-cosmetics/pirate_eyepatch_v01.png",
    "sourceBounds": [
      23,
      447,
      1210,
      366
    ],
    "preview": {
      "width": 1254,
      "height": 1254,
      "viewBox": [
        -49.60000000000002,
        65.33333333333326,
        1355.2,
        1129.3333333333335
      ]
    }
  },
  "freckles": {
    "file": "candidates/accessories/lot_013/2026-09-20-cosmetics/freckles_v02.png",
    "sourceBounds": [
      55,
      500,
      1159,
      288
    ],
    "preview": {
      "width": 1254,
      "height": 1254,
      "viewBox": [
        -14.540000000000077,
        103.13333333333321,
        1298.0800000000002,
        1081.7333333333336
      ]
    }
  },
  "nose_piercing": {
    "file": "candidates/accessories/lot_013/2026-09-20-cosmetics/nose_piercing_v01.png",
    "sourceBounds": [
      164,
      355,
      726,
      863
    ],
    "preview": {
      "width": 1049,
      "height": 1499,
      "viewBox": [
        -52.936000000000035,
        303.21999999999997,
        1159.872,
        966.5600000000001
      ]
    }
  },
  "ear_piercing": {
    "file": "candidates/accessories/lot_013/2026-09-20-cosmetics/ear_piercing_v01.png",
    "sourceBounds": [
      146,
      170,
      784,
      1116
    ],
    "preview": {
      "width": 1060,
      "height": 1484,
      "viewBox": [
        -211.952,
        103.03999999999996,
        1499.904,
        1249.92
      ]
    }
  },
  "scar": {
    "file": "candidates/accessories/lot_013/2026-09-20-cosmetics/scar_v01.png",
    "sourceBounds": [
      514,
      93,
      314,
      1074
    ],
    "preview": {
      "width": 1246,
      "height": 1263,
      "viewBox": [
        -50.728000000000065,
        28.559999999999945,
        1443.4560000000001,
        1202.88
      ]
    }
  },
  "diamond_necklace": {
    "file": "candidates/accessories/lot_013/2026-09-20-cosmetics/diamond_necklace_v01.png",
    "sourceBounds": [
      80,
      40,
      1759,
      727
    ],
    "preview": {
      "width": 1918,
      "height": 820,
      "viewBox": [
        -25.540000000000077,
        -417.3666666666668,
        1970.0800000000002,
        1641.7333333333336
      ]
    }
  }
};
