"""Copy selected imagegen PNGs unchanged and record their explicit sprite bounds."""
import hashlib
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
RELATIVE = Path("candidates/accessories/lot_013/2026-09-20-cosmetics")
WORKSHOP = ROOT / ".Tmp/avatar/avatar/assets" / RELATIVE
PUBLIC = ROOT / "public/avatars/v1" / RELATIVE


def keep(target, data):
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and target.read_bytes() != data:
        raise RuntimeError(f"Use a new version instead of replacing {target}")
    if not target.exists():
        target.write_bytes(data)


def main():
    sources = json.loads((ROOT / "dev/avatar-accessories/sources.json").read_text(encoding="utf-8"))
    geometry, report = {}, {}
    for identifier, spec in sources.items():
        source = Path(spec["path"])
        data = source.read_bytes()
        filename = f"{identifier}_v{spec.get('version', '01')}.png"
        with Image.open(source) as image:
            if image.mode != "RGBA":
                raise RuntimeError(f"Missing RGBA: {source}")
            alpha = image.getchannel("A")
            if alpha.getextrema() != (0, 255):
                raise RuntimeError(f"Missing real transparency or opaque artwork: {source}")
            bounds = alpha.point(lambda value: 255 if value > 8 else 0).getbbox()
            x, y, right, bottom = bounds
            width, height = right-x, bottom-y
            frame_height = max(height, width / 1.2) * 1.12
            frame_width = frame_height * 1.2
            geometry[identifier] = {
                "file": (RELATIVE / filename).as_posix(),
                "sourceBounds": [x, y, width, height],
                "preview": {"width": image.width, "height": image.height,
                    "viewBox": [x+width/2-frame_width/2, y+height/2-frame_height/2, frame_width, frame_height]},
            }
            report[identifier] = {"result": filename, "size": list(image.size), "alpha": list(alpha.getextrema()),
                "sha256": hashlib.sha256(data).hexdigest(), "source": spec, "status": "candidate"}
        keep(WORKSHOP / filename, data)
        keep(PUBLIC / filename, data)
    (ROOT / "shared/avatarCosmeticImages.js").write_text(
        "// Generated by scripts/prepare-avatar-cosmetics.py; pixels remain unchanged.\n"
        + "export const AVATAR_COSMETIC_IMAGES = " + json.dumps(geometry, indent=2) + ";\n", encoding="utf-8")
    (WORKSHOP / "manifest.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({key: value['sourceBounds'] for key, value in geometry.items()}))


if __name__ == "__main__":
    main()
