"""Copy imagegen PNG bytes unchanged and measure alpha for runtime placement."""
import hashlib
import json
from pathlib import Path
import shutil
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
sources = json.loads((ROOT / "dev/avatar-additions/sources.json").read_text(encoding="utf-8"))
metadata = {}
for entry in sources["assets"]:
    source = Path(entry["source"])
    relative = f"additions/2026-09-22/{entry['id']}.png"
    target = ROOT / "public/avatars/v1" / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and target.read_bytes() != source.read_bytes():
        raise RuntimeError(f"Refusing to overwrite {target}")
    shutil.copyfile(source, target)
    with Image.open(target) as image:
        if image.mode != "RGBA" or image.getchannel("A").getextrema() != (0, 255):
            raise RuntimeError(f"Missing native transparency: {source}")
        left, top, right, bottom = image.getchannel("A").point(lambda a: 255 if a >= 8 else 0).getbbox()
        width, height = right - left, bottom - top
        # The shop frame is 6:5. Crop coordinates affect display, never the PNG.
        frame_height = max(height, width / 1.2) * 1.12
        frame_width = frame_height * 1.2
        metadata[entry["id"]] = {
            "file": relative,
            "sourceBounds": [left, top, width, height],
            "preview": {"width": image.width, "height": image.height,
                        "viewBox": [round((left + right - frame_width) / 2, 2),
                                    round((top + bottom - frame_height) / 2, 2),
                                    round(frame_width, 2), round(frame_height, 2)]},
        }
    entry["sha256"] = hashlib.sha256(target.read_bytes()).hexdigest()
    entry["file"] = relative
    print(entry["id"], metadata[entry["id"]]["sourceBounds"])

(ROOT / "shared/avatarAdditionImages.js").write_text(
    "// Generated by scripts/prepare-avatar-additions.py; original imagegen PNGs remain intact.\n"
    "export const AVATAR_ADDITION_IMAGES = Object.freeze("
    + json.dumps(metadata, indent=2, ensure_ascii=False) + ");\n", encoding="utf-8")
(ROOT / "dev/avatar-additions/manifest.json").write_text(
    json.dumps(sources, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
