export const avatarPresets = {
  goblinGreen: {
    genderPresentation: "masculine",
    bodyShape: "blob",
    bodyColor: "#2ecc71",
    secondaryColor: "#0f9f8f",
    skinColor: "#f2c6a0",
    hairColor: "#273447",
    eyeStyle: "round",
    pupilStyle: "normal",
    mouthStyle: "smile",
    accessory: "none",
    hair: "short",
    horns: "small",
    pattern: "spots",
  },
  blueBlob: {
    genderPresentation: "feminine",
    bodyShape: "blob",
    bodyColor: "#4d8dff",
    secondaryColor: "#1e5fbf",
    skinColor: "#ffd9bd",
    hairColor: "#3b2a20",
    eyeStyle: "wide",
    pupilStyle: "normal",
    mouthStyle: "open",
    accessory: "none",
    hair: "bob",
    horns: "none",
    pattern: "stripes",
  },
  scholarMonster: {
    genderPresentation: "masculine",
    bodyShape: "round",
    bodyColor: "#2d98da",
    secondaryColor: "#f6b93b",
    skinColor: "#e8b887",
    hairColor: "#2f3542",
    eyeStyle: "sleepy",
    pupilStyle: "normal",
    mouthStyle: "neutral",
    accessory: "glasses",
    hair: "short",
    horns: "none",
    pattern: "none",
  },
  angryTomato: {
    genderPresentation: "feminine",
    bodyShape: "round",
    bodyColor: "#e84118",
    secondaryColor: "#fbc531",
    skinColor: "#f1b27a",
    hairColor: "#6d2e1f",
    eyeStyle: "sleepy",
    pupilStyle: "normal",
    mouthStyle: "sad",
    accessory: "none",
    hair: "curly",
    horns: "none",
    pattern: "spots",
  },
  goldenGobble: {
    genderPresentation: "feminine",
    bodyShape: "square",
    bodyColor: "#f9ca24",
    secondaryColor: "#f0932b",
    skinColor: "#f6c79b",
    hairColor: "#8e5a2a",
    eyeStyle: "wide",
    pupilStyle: "normal",
    mouthStyle: "smile",
    accessory: "crown",
    hair: "bob",
    horns: "none",
    pattern: "stripes",
  },
};

export const defaultAvatarConfig = avatarPresets.goblinGreen;
