export const REALTIME_STATE_FIELDS = Object.freeze([
  "announcements",
  "breakCountdown",
  "breakKind",
  "finalResults",
  "lobbyPlayersList",
  "lobbyPlayersLoading",
  "lobbyRoomStatus",
  "medals",
  "nextStartAt",
  "players",
  "provisionalRanking",
  "roomsStats",
  "roundId",
  "roundPreparing",
  "roundStartDelayTick",
  "roundStats",
  "serverEndsAt",
  "serverRoundDurationMs",
  "specialRound",
  "targetSummary",
  "tournament",
  "tournamentFinaleHoldUntil",
  "tournamentLobby",
  "tournamentRanking",
  "tournamentRoundPoints",
  "tournamentSummary",
  "tournamentSummaryAt",
  "tournamentTotals",
  "upcomingSpecial",
]);

export const REALTIME_STATE_FIELD_SET = new Set(REALTIME_STATE_FIELDS);

export function createInitialRealtimeState() {
  return Object.freeze({
    announcements: [],
    breakCountdown: null,
    breakKind: null,
    finalResults: [],
    lobbyPlayersList: [],
    lobbyPlayersLoading: false,
    lobbyRoomStatus: null,
    medals: {},
    nextStartAt: null,
    players: [],
    provisionalRanking: [],
    roomsStats: [],
    roundId: null,
    roundPreparing: null,
    roundStartDelayTick: 0,
    roundStats: null,
    serverEndsAt: null,
    serverRoundDurationMs: null,
    specialRound: null,
    targetSummary: null,
    tournament: null,
    tournamentFinaleHoldUntil: null,
    tournamentLobby: null,
    tournamentRanking: [],
    tournamentRoundPoints: {},
    tournamentSummary: null,
    tournamentSummaryAt: null,
    tournamentTotals: {},
    upcomingSpecial: null,
  });
}
